# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 20:11
from __future__ import unicode_literals

import Restaurant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=30)),
                ('Menu_Name', models.CharField(max_length=30)),
                ('Dish', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=30)),
                ('Menu', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant', models.CharField(max_length=40)),
                ('slug', models.SlugField(unique=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=Restaurant.models.upload_location)),
                ('Address', models.TextField(max_length=200)),
                ('Area', models.CharField(max_length=40)),
                ('City', models.CharField(max_length=40)),
                ('Pin_Code', models.CharField(max_length=10)),
                ('Cuisine', models.CharField(max_length=500)),
                ('Minimum_Rate', models.CharField(max_length=4)),
                ('Time_To_Delivery', models.CharField(max_length=3)),
                ('Phone', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_restaurant', to='Restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='Menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_menu', to='Restaurant.Menu'),
        ),
        migrations.AddField(
            model_name='dish',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_restaurant', to='Restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
