# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_auto_20161217_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='Restaurant',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Restaurant',
        ),
    ]
