# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20161217_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_restaurant', to='Restaurant.Restaurant'),
            preserve_default=False,
        ),
    ]
