# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.PositiveIntegerField()),
                ('Restaurant', models.CharField(max_length=30)),
                ('restaurant_id', models.PositiveIntegerField()),
                ('Menu', models.CharField(max_length=50)),
                ('Dish', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=4)),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
